name: Create_New_Branch

permissions:
  contents: write
  actions: write

on: 
  workflow_dispatch:

jobs:
  create_new_branch:
    runs-on: ubuntu-latest
    steps:
      - name: create-new-branch
        uses: gendloop/create-new-branch@main
        with: 
          ref_branch: 'main'
          branch: 'dev'

      